[package]
name = "middb-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "middb_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22"
middb-core = { path = "../../crates/middb-core" }
